services:
  mariadb:
    image: mariadb:11
    container_name: coffeeandstudy-mariadb
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: coffeeandstudy
      MARIADB_USER: coffeeuser
      MARIADB_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: ibone93/coffeeandstudy-api:latest
    container_name: coffeeandstudy-api
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: coffeeandstudy
      DB_USER: coffeeuser
      DB_PASSWORD: 1234
    ports:
      - "8080:8080"

volumes:
  mariadb_data: